#!/bin/bash


if [ $# -gt 2 ]; then
	echo "Use it to update all the submodules of this repository and "
	echo "commit+push the changes (the commit will contain the today's date):"
	echo ""
	echo " -> usage: git-update-submodules [branch=devel/master]"
	echo ""
elif [ $# -eq 1 ]; then
	branch=$1
else
	branch=devel
fi

function co_to_br_or_master() {

	local br=devel
	local git_status=$(git checkout $br 2>&1)
	local error_str="error: pathspec 'devel' did not match*"

	if [[ $git_status == $error_str ]]; then
		echo "$br branch not found. Trying master..."
    	git checkout master
    else
    	echo $git_status
    fi
	}

git submodule foreach "export git_status=$(git checkout $branch 2>&1);
                       if [[ $git_status == "error: pathspec 'devel' did not match*" ]]
                       then
                       	 echo "$br branch not found. Trying master..."
                       	 git checkout master
                       else
                       	 echo $git_status
                       fi
                       git pull --prune; echo "

cmName="Updating the submodules for $branch branch on $(date +"%d/%m/%Y")"
echo "Commiting it with name '$cmName'"
git commit -am "$cmName"

echo "Pushing it..."
git push
