#!/bin/bash

function usage
{
	echo "Use it to register all the plugins inside the PLUGINS_HOME and XMIPP_HOME "
	echo "to scipion. It's done via symbolic link (default) or via PYTHONPATH (-env) "
	echo ""
	echo " -> usage: source plugins-register [options]"
	echo "       options: SCIPION_HOME = ~/scipion"
	echo "                PLUGINS_HOME = ~/scipion-em"
	echo "                XMIPP_HOME   = ~/xmipp-bundle"
	echo "                -env : to set the PYTHONPATH instead of making a symbolic link"
	echo ""
	echo "   example: source plugins-register SCIPION_HOME=~/scipion-pluginized PLUGINS_HOME=~/plugins2scipion"
	mode='exit'
}

mode='ln'
SCIPION_HOME=~/scipion
PLUGINS_HOME=~/scipion-em
XMIPP_HOME=~/xmipp-bundle
for var in "$@"
do
	case "$var" in
		XMIPP_HOME=*)
			`$var`
			;;
		PLUGINS_HOME=*)
			`$var`
			;;
		SCIPION_HOME=*)
			`$var`
			;;
		'-env')
			mode='env'
			;;
		*)
			echo "...error: param "$var" is not understood"
			echo ""
			usage
	esac
done

echo "XMIPP_HOME="$XMIPP_HOME
echo "PLUGINS_HOME="$PLUGINS_HOME
echo "SCIPION_HOME="$SCIPION_HOME

if [ $mode == 'env' ]
then

	export PYTHONPATH=$XMIPP_HOME/src/scipion-em-xmipp:$PYTHONPATH

	scipionPlugins=`ls -d $PLUGINS_HOME/scipion-em-*`
	for plugin in $scipionPlugins
	do
		export PYTHONPATH=$plugin:$PYTHONPATH
	done

	echo ""
	echo "scipion plugins installed via setting PYTHONPATH"
	echo ""
	echo "PYTHONPATH="$PYTHONPATH
	echo ""
	echo "please run 'echo \$PYTHONPATH' to check that is correct."
	echo "If it's not correct, make sure that you run it as 'source plugins-register'"

elif [ $mode == 'exit' ]
then
	echo ""

else

	plugDest = $SCIPION_HOME/software/lib/python2.7/site-packages
	ln -sf $XMIPP_HOME/src/scipion-em-xmipp/xmipp3 $plugDest/

	scipionPlugins=`ls -d $PLUGINS_HOME/scipion-em-*`
	for plugin in $scipionPlugins
	do
		ln -sf $plugin $plugDest/
	done
	ls -l $plugDest/

fi
